(define (problem car_prob)
    (:domain car)
    (:objects mycar)
    (:init (not (engineBlown mycar))
            (running mycar)
	    (transmission_fine mycar)
	    (= (running_time mycar) 0)
	    (= (up_limit mycar) 2)
	    (= (down_limit mycar) -2)
            (= (d mycar) 0)
            (= (a mycar) 0)
            (= (v mycar) 0))
     (:goal (and (goal_reached mycar) (not(engineBlown mycar)) (<= (running_time mycar) 50) (transmission_fine mycar) ))
)
